In [1]:
import pandas as pd

# Préparation des données

In [2]:
rbx = pd.read_csv("extractions/bib_titres_20251130.csv.gz")

rbx.loc[rbx['ccodes'].isna(), 'ccodes'] = 'N#A'
rbx.loc[rbx['ccodes'].str.contains('JBD'), 'public'] = 'jeunesse'
rbx.loc[rbx['ccodes'].str.contains('AAPBD'), 'public'] = 'adultes'
rbx.loc[rbx['ccodes'].str.contains('AAPBD'), 'genre'] = 'bd'
rbx.loc[rbx['ccodes'].str.contains('JBD'), 'genre'] = 'bd'

rbx.loc[(~rbx['bib_ark_bnf'].isna()) & (rbx['bib_ark_bnf'].str.contains('ark')), 'bib_alignement_bnf'] = True

filters_rbx = []
for c in rbx.columns:
    if c[0] == 'B':
        c2 = c + "_"
        filters_rbx.append(c2)
        rbx[c2] = False
        rbx.loc[~rbx[c].isna(), c2] = True

gr = df.groupby(filters_bnf)['bib_record_id'].count().reset_index().sort_values(by='bib_record_id', ascending=False) #.to_excel("resultats/titres_gr_20251109.xlsx", index=False)

/tmp/ipykernel_5932/1243612876.py:1: DtypeWarning: Columns (9,11,15,17,18,19,20,22,25) have mixed types. Specify dtype option on import or set low_memory=False.
  rbx = pd.read_csv("extractions/bib_titres_20251130.csv.gz")

In [3]:
bnf = pd.read_csv("extractions/all_bnf_records_titres.csv.gz")

filters_bnf = []
for c in bnf.columns:
    if c[0] == 'B':
        c2 = c + "_bnf_"
        filters_bnf.append(c2)
        bnf[c2] = False
        bnf.loc[~bnf[c].isna(), c2] = True
    bnf = bnf.rename(columns={c: f"{c}_bnf"})
bnf['bib_persistentid_bnf'] = bnf['bib_persistentid_bnf'].str.replace('http://catalogue.bnf.fr/', '')

/tmp/ipykernel_5932/1255788967.py:1: DtypeWarning: Columns (20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  bnf = pd.read_csv("extractions/all_bnf_records_titres.csv.gz")

In [6]:
rbx_bnf = rbx.merge(bnf, left_on = 'bib_ark_bnf', right_on = 'bib_persistentid_bnf', how= 'inner')
len(rbx_bnf)

121859

In [8]:
# Cas des 200h et 461v répétés
cas1 = rbx[
       ( rbx['B200h_'] == True )
     & ( rbx['B461v_'] == True )
]

In [9]:
cas1.groupby(['bib_agence_cat', 'bib_rbx_vdg_action', 'bib_pat'])['bib_record_id'].count()

bib_agence_cat          bib_rbx_vdg_action                   bib_pat
ADAV                    autorités seulement                  False        21
                        notice bibliographique et autorités  False         2
BnF                     aucune action                        False       315
                                                             True          8
                        autorités seulement                  False      1024
                        notice bibliographique et autorités  False      3317
                                                             True          3
Electre                 aucune action                        False        22
                                                             True          4
                        autorités seulement                  False       154
                        notice bibliographique et autorités  False       712
                                                             True          3
Médiathèque de Roubaix  autorités seulement                  False         2
autre                   autorités seulement                  False         1
                        notice bibliographique et autorités  False         4
Name: bib_record_id, dtype: int64

In [20]:
cas1[(cas1['bib_agence_cat'] == 'BnF') & (cas1['bib_rbx_vdg_action'] == 'notice bibliographique et autorités')].sample(n=5)

,bib_record_id,bib_ark_bnf,bib_rbx_date_creation_notice,bib_rbx_vdg_action,bib_rbx_support,B200ae,B200h,B200i,B200v,B225a,...,B225a_,B225h_,B225i_,B225v_,B225x_,B410a_,B410t_,B410v_,B461t_,B461v_
167066,302232,ark:/12148/cb45009440p,2017-11-16,notice bibliographique et autorités,Livre,Le vocabulaire des philosophes,1,De l'Antiquité à la Renaissance,NaN,Ellipses poche,...,True,False,False,False,False,False,True,False,True,True
146777,271252,ark:/12148/cb44200800k,2014-10-23,notice bibliographique et autorités,Livre,Metropolis,2,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,True,True
198995,342716,ark:/12148/cb466479788,2021-12-04,notice bibliographique et autorités,Livre,Magus of the library,4,NaN,NaN,Kizuna,...,True,False,False,False,False,False,True,False,True,True
163471,297208,ark:/12148/cb45193236g,2017-04-13,notice bibliographique et autorités,Livre,Les enquêtes de Violette,1,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,True,True
148622,274278,ark:/12148/cb43782137v,2015-02-17,notice bibliographique et autorités,Livre,Gisèle Alain,4,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,True,True

In [14]:
cas1_bnf = bnf[
       ( bnf['B200h_bnf_'] == True )
     & ( bnf['B461v_bnf_'] == True )
]
cas1_bnf

,bib_record_id_bnf,bib_persistentid_bnf,bib_ark_bnf_bnf,bib_rbx_date_creation_notice_bnf,bib_rbx_vdg_action_bnf,bib_rbx_support_bnf,B200ae_bnf,B200h_bnf,B200i_bnf,B200v_bnf,...,B410t_bnf_,B410v_bnf_,B461t_bnf_,B461v_bnf_,B462t_bnf_,B462v_bnf_,B463t_bnf_,B463v_bnf_,B464t_bnf_,B464v_bnf_
116,FRBNF366062470000005,ark:/12148/cb36606247w,NaN,NaN,NaN,NaN,La Lecture et ses institutions 1700-1830,1,Prélude,NaN,...,False,False,True,True,False,False,False,False,False,False
178,FRBNF351277480000006,ark:/12148/cb351277488,NaN,NaN,NaN,NaN,Autobiographie de Giuliano di Sansevero,4,Les Puissances,NaN,...,False,False,True,True,False,False,False,False,False,False
179,FRBNF35129282000000X,ark:/12148/cb35129282j,NaN,NaN,NaN,NaN,Autobiographie de Giuliano di Sansevero,5,Le Dernier des Sansevero,NaN,...,False,False,True,True,False,False,False,False,False,False
312,FRBNF355364720000005,ark:/12148/cb35536472z,NaN,NaN,NaN,NaN,Histoire de la France rurale de 1340 à 1789,2,L'âge classique des paysans,NaN,...,True,True,True,True,False,False,False,False,False,False
313,FRBNF355364780000009,ark:/12148/cb355364781,NaN,NaN,NaN,NaN,Histoire de la France rurale depuis 1914,4,La fin de la France paysanne,NaN,...,True,True,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119657,FRBNF475202090000004,ark:/12148/cb47520209c,NaN,NaN,NaN,NaN,Kiara diamant écorché par le sang,Tome 1,NaN,NaN,...,False,False,True,True,False,False,False,False,False,False
119658,FRBNF475841110000007,ark:/12148/cb47584111v,NaN,NaN,NaN,NaN,Kiara diamant écorché par le sang,Tome 2,NaN,NaN,...,False,False,True,True,False,False,False,False,False,False
119659,FRBNF486051620000006,ark:/12148/cb48605162n,NaN,NaN,NaN,NaN,Kiara diamant écorché par le sang,Tome 3,NaN,NaN,...,False,False,True,True,False,False,False,False,False,False
119730,FRBNF486037100000003,ark:/12148/cb48603710k,NaN,NaN,NaN,NaN,Simone,3,"Mais un jour dans notre vie, le printemps refl...",NaN,...,False,False,True,True,False,False,False,False,False,False
119781,FRBNF485993570000005,ark:/12148/cb485993578,NaN,NaN,NaN,NaN,Dissidentes,Livre 1,NaN,NaN,...,False,False,True,True,False,False,False,False,False,False

In [21]:
# Pas de 200h mais existe un 461v
cas2 = df[
       ( df['B200h_'] == False )
     & ( df['B461v_'] == True )
]

In [22]:
len(cas2)

6876

In [23]:
cas2.sample(n=5)

,bib_record_id,bib_ark_bnf,bib_rbx_date_creation_notice,bib_rbx_vdg_action,bib_rbx_support,B200ae,B200h,B200i,B200v,B225a,...,B225a_,B225h_,B225i_,B225v_,B225x_,B410a_,B410t_,B410v_,B461t_,B461v_
179366,318608,ark:/12148/cb457502406,2019-06-20,notice bibliographique et autorités,Livre,L'identité Osborn,NaN,NaN,NaN,All-new Amazing Spider-Man ; Marvel now !,...,True,False,False,True,False,False,True,False,True,True
211735,356922,ark:/12148/cb47263364t,2023-06-02,notice bibliographique et autorités,Livre,Fiona la rebelle roman,NaN,NaN,NaN,La saison des débutantes,...,True,False,False,True,False,False,False,False,True,True
192185,334920,ark:/12148/cb46663620k,2021-02-19,notice bibliographique et autorités,Livre,Tisgo,NaN,NaN,NaN,Mekka Nikki ; Grand souk,...,True,False,False,True,False,False,True,False,True,True
180966,320561,ark:/12148/cb457927208,2019-09-26,notice bibliographique et autorités,Livre,Bivouac attack !,NaN,NaN,NaN,Shaker monster,...,True,False,False,True,False,False,False,False,True,True
191771,334439,ark:/12148/cb45604839d,2021-02-11,notice bibliographique et autorités,Livre,Bring the kids home,NaN,NaN,NaN,Freaks' squeele Funérailles,...,True,False,False,True,False,False,False,False,True,True

In [ ]:
# on compare les notices vendangées avec les notices bnf

In [26]:
vdg_ok = df_bnf[
    (df_bnf['B200ae_'] == df_bnf['B200ae_bnf_'])
    & (df_bnf['B200h_'] == df_bnf['B200h_bnf_'])
    & (df_bnf['B200i_'] == df_bnf['B200i_bnf_'])
    & (df_bnf['B200v_'] == df_bnf['B200v_bnf_'])
    & (df_bnf['B225a_'] == df_bnf['B225a_bnf_'])
    & (df_bnf['B225h_'] == df_bnf['B225h_bnf_'])
    & (df_bnf['B225i_'] == df_bnf['B225i_bnf_'])
    & (df_bnf['B225v_'] == df_bnf['B225v_bnf_'])
    & (df_bnf['B225x_'] == df_bnf['B225x_bnf_'])
    & (df_bnf['B410a_'] == df_bnf['B410a_bnf_'])
    & (df_bnf['B410t_'] == df_bnf['B410t_bnf_'])
    & (df_bnf['B410v_'] == df_bnf['B410v_bnf_'])
    & (df_bnf['B461t_'] == df_bnf['B461t_bnf_'])
    & (df_bnf['B461v_'] == df_bnf['B461v_bnf_'])
]
len(vdg_ok)

103876

In [27]:
vdg_ko = df_bnf[~df_bnf['bib_record_id'].isin(vdg_ok['bib_record_id'])]
vdg_ko = vdg_ko[vdg_ko['bib_rbx_vdg_action'] == 'notice bibliographique et autorités']
len(vdg_ko)

11425

In [28]:
vdg_ko[
    (vdg_ko['B200h_'] != vdg_ko['B200h_bnf_'])
]

Empty DataFrame
Columns: [bib_record_id, bib_persistentid, bib_ark_bnf, bib_rbx_date_creation_notice, bib_rbx_vdg_action, bib_rbx_support, B200ae, B200h, B200i, B200v, B225a, B225h, B225i, B225v, B225x, B410a, B410t, B410v, B461t, B461v, bib_agence_cat, bib_pat, ccodes, bib_nb_items, public, genre, bib_alignement_bnf, B200ae_, B200h_, B200i_, B200v_, B225a_, B225h_, B225i_, B225v_, B225x_, B410a_, B410t_, B410v_, B461t_, B461v_, bib_record_id_bnf, bib_persistentid_bnf, bib_ark_bnf_bnf, bib_rbx_date_creation_notice_bnf, bib_rbx_vdg_action_bnf, bib_rbx_support_bnf, B200ae_bnf, B200h_bnf, B200i_bnf, B200v_bnf, B225a_bnf, B225h_bnf, B225i_bnf, B225v_bnf, B225x_bnf, B410a_bnf, B410t_bnf, B410v_bnf, B461t_bnf, B461v_bnf, bib_agence_cat_bnf, bib_pat_bnf, ccodes_bnf, bib_nb_items_bnf, B200ae_bnf_, B200h_bnf_, B200i_bnf_, B200v_bnf_, B225a_bnf_, B225h_bnf_, B225i_bnf_, B225v_bnf_, B225x_bnf_, B410a_bnf_, B410t_bnf_, B410v_bnf_, B461t_bnf_, B461v_bnf_]
Index: []

[0 rows x 79 columns]

In [29]:
vdg_ko[

    (vdg_ko['B200i_'] != vdg_ko['B200i_bnf_'])
]

Empty DataFrame
Columns: [bib_record_id, bib_persistentid, bib_ark_bnf, bib_rbx_date_creation_notice, bib_rbx_vdg_action, bib_rbx_support, B200ae, B200h, B200i, B200v, B225a, B225h, B225i, B225v, B225x, B410a, B410t, B410v, B461t, B461v, bib_agence_cat, bib_pat, ccodes, bib_nb_items, public, genre, bib_alignement_bnf, B200ae_, B200h_, B200i_, B200v_, B225a_, B225h_, B225i_, B225v_, B225x_, B410a_, B410t_, B410v_, B461t_, B461v_, bib_record_id_bnf, bib_persistentid_bnf, bib_ark_bnf_bnf, bib_rbx_date_creation_notice_bnf, bib_rbx_vdg_action_bnf, bib_rbx_support_bnf, B200ae_bnf, B200h_bnf, B200i_bnf, B200v_bnf, B225a_bnf, B225h_bnf, B225i_bnf, B225v_bnf, B225x_bnf, B410a_bnf, B410t_bnf, B410v_bnf, B461t_bnf, B461v_bnf, bib_agence_cat_bnf, bib_pat_bnf, ccodes_bnf, bib_nb_items_bnf, B200ae_bnf_, B200h_bnf_, B200i_bnf_, B200v_bnf_, B225a_bnf_, B225h_bnf_, B225i_bnf_, B225v_bnf_, B225x_bnf_, B410a_bnf_, B410t_bnf_, B410v_bnf_, B461t_bnf_, B461v_bnf_]
Index: []

[0 rows x 79 columns]

In [30]:
vdg_ko[
    (vdg_ko['B200v_'] != vdg_ko['B200v_bnf_'])
]

,bib_record_id,bib_persistentid,bib_ark_bnf,bib_rbx_date_creation_notice,bib_rbx_vdg_action,bib_rbx_support,B200ae,B200h,B200i,B200v,...,B225a_bnf_,B225h_bnf_,B225i_bnf_,B225v_bnf_,B225x_bnf_,B410a_bnf_,B410t_bnf_,B410v_bnf_,B461t_bnf_,B461v_bnf_
89756,321926,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45821701g,2019-11-05,notice bibliographique et autorités,Livre audio,"Millénium, Vol. 6 La fille qui devait mourir",NaN,NaN,6,...,True,False,False,True,False,False,False,False,True,True

In [32]:
vdg_ko[
    (vdg_ko['B225a_'] != vdg_ko['B225a_bnf_'])
]

,bib_record_id,bib_persistentid,bib_ark_bnf,bib_rbx_date_creation_notice,bib_rbx_vdg_action,bib_rbx_support,B200ae,B200h,B200i,B200v,...,B225a_bnf_,B225h_bnf_,B225i_bnf_,B225v_bnf_,B225x_bnf_,B410a_bnf_,B410t_bnf_,B410v_bnf_,B461t_bnf_,B461v_bnf_
28372,122578,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb318265186,2014-06-30,notice bibliographique et autorités,Livre,Naissance d'une culture. Quatrièmes essais pou...,NaN,NaN,NaN,...,True,False,False,False,False,False,True,False,False,False
87564,318464,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45833188d,2019-06-19,notice bibliographique et autorités,Livre audio,Bien gérer son temps pour les nuls,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89488,321460,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45682704n,2019-10-24,notice bibliographique et autorités,Livre audio,Ca raconte Sarah suivi d'un entretien avec l'a...,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
89489,321463,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb451016754,2019-10-24,notice bibliographique et autorités,Livre audio,Le coma des mortels,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89496,321471,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb457381304,2019-10-24,notice bibliographique et autorités,Livre audio,Un mariage anglais,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89502,321479,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45794319f,2019-10-24,notice bibliographique et autorités,Livre audio,Le troisième jumeau,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89725,321888,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb414890720,2019-11-05,notice bibliographique et autorités,Livre audio,Les fourmis Le loup-garou et autres nouvelles,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89764,321935,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45824973m,2019-11-05,notice bibliographique et autorités,Livre audio,La cage dorée la vengeance d'une femme est dou...,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89765,321936,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45794301c,2019-11-05,notice bibliographique et autorités,Livre audio,Civilizations,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89766,321937,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45824983x,2019-11-05,notice bibliographique et autorités,Livre audio,Salina les trois exils,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89768,321939,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb457943032,2019-11-05,notice bibliographique et autorités,Livre audio,Né d'aucune femme,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89772,321943,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45810817p,2019-11-05,notice bibliographique et autorités,Livre audio,L'automne à Pékin roman,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89773,321944,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb458108108,2019-11-05,notice bibliographique et autorités,Livre audio,Journal d'un amour perdu,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89774,321945,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45810823m,2019-11-05,notice bibliographique et autorités,Livre audio,Octobre,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89775,321946,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb458331961,2019-11-05,notice bibliographique et autorités,Livre audio,Zen ! la méditation pour les nuls,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
89779,321950,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45832685h,2019-11-05,notice bibliographique et autorités,Livre audio,Les victorieuses,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
121730,378180,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb48621028n,2025-10-29,notice bibliographique et autorités,Livre,Dans la nuit solitaire,NaN,NaN,NaN,...,True,False,False,False,False,False,True,False,False,False
121850,378449,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb48617644s,2025-11-08,notice bibliographique et autorités,Livre,Astronomie,NaN,NaN,NaN,...,False,False,False,True,False,False,False,False,False,False

In [33]:
vdg_ko[
    (vdg_ko['B225v_'] != vdg_ko['B225v_bnf_'])
]

,bib_record_id,bib_persistentid,bib_ark_bnf,bib_rbx_date_creation_notice,bib_rbx_vdg_action,bib_rbx_support,B200ae,B200h,B200i,B200v,...,B225a_bnf_,B225h_bnf_,B225i_bnf_,B225v_bnf_,B225x_bnf_,B410a_bnf_,B410t_bnf_,B410v_bnf_,B461t_bnf_,B461v_bnf_
89770,321941,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45832652j,2019-11-05,notice bibliographique et autorités,Livre audio,"Les femmes écrivains Simone de Beauvoir, Margu...",NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False

In [34]:
vdg_ko[
    (vdg_ko['B410a_'] != vdg_ko['B410a_bnf_'])
]

Empty DataFrame
Columns: [bib_record_id, bib_persistentid, bib_ark_bnf, bib_rbx_date_creation_notice, bib_rbx_vdg_action, bib_rbx_support, B200ae, B200h, B200i, B200v, B225a, B225h, B225i, B225v, B225x, B410a, B410t, B410v, B461t, B461v, bib_agence_cat, bib_pat, ccodes, bib_nb_items, public, genre, bib_alignement_bnf, B200ae_, B200h_, B200i_, B200v_, B225a_, B225h_, B225i_, B225v_, B225x_, B410a_, B410t_, B410v_, B461t_, B461v_, bib_record_id_bnf, bib_persistentid_bnf, bib_ark_bnf_bnf, bib_rbx_date_creation_notice_bnf, bib_rbx_vdg_action_bnf, bib_rbx_support_bnf, B200ae_bnf, B200h_bnf, B200i_bnf, B200v_bnf, B225a_bnf, B225h_bnf, B225i_bnf, B225v_bnf, B225x_bnf, B410a_bnf, B410t_bnf, B410v_bnf, B461t_bnf, B461v_bnf, bib_agence_cat_bnf, bib_pat_bnf, ccodes_bnf, bib_nb_items_bnf, B200ae_bnf_, B200h_bnf_, B200i_bnf_, B200v_bnf_, B225a_bnf_, B225h_bnf_, B225i_bnf_, B225v_bnf_, B225x_bnf_, B410a_bnf_, B410t_bnf_, B410v_bnf_, B461t_bnf_, B461v_bnf_]
Index: []

[0 rows x 79 columns]

In [35]:
vdg_ko[
    (vdg_ko['B410t_'] != vdg_ko['B410t_bnf_'])
]

,bib_record_id,bib_persistentid,bib_ark_bnf,bib_rbx_date_creation_notice,bib_rbx_vdg_action,bib_rbx_support,B200ae,B200h,B200i,B200v,...,B225a_bnf_,B225h_bnf_,B225i_bnf_,B225v_bnf_,B225x_bnf_,B410a_bnf_,B410t_bnf_,B410v_bnf_,B461t_bnf_,B461v_bnf_
28372,122578,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb318265186,2014-06-30,notice bibliographique et autorités,Livre,Naissance d'une culture. Quatrièmes essais pou...,NaN,NaN,NaN,...,True,False,False,False,False,False,True,False,False,False
87563,318463,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb458332086,2019-06-19,notice bibliographique et autorités,Livre audio,Gérer son stress pour les nuls,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
87564,318464,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45833188d,2019-06-19,notice bibliographique et autorités,Livre audio,Bien gérer son temps pour les nuls,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89489,321463,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb451016754,2019-10-24,notice bibliographique et autorités,Livre audio,Le coma des mortels,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89496,321471,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb457381304,2019-10-24,notice bibliographique et autorités,Livre audio,Un mariage anglais,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89502,321479,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45794319f,2019-10-24,notice bibliographique et autorités,Livre audio,Le troisième jumeau,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89725,321888,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb414890720,2019-11-05,notice bibliographique et autorités,Livre audio,Les fourmis Le loup-garou et autres nouvelles,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89740,321906,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45718463h,2019-11-05,notice bibliographique et autorités,Livre audio,Deux soeurs,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
89742,321910,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45710265q,2019-11-05,notice bibliographique et autorités,Livre audio,L'égarée,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
89746,321914,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45772719n,2019-11-05,notice bibliographique et autorités,Livre audio,Les sept mariages d'Edgar et Ludmilla,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
89748,321917,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45723436m,2019-11-05,notice bibliographique et autorités,Livre audio,Dans le murmure des feuilles qui dansent,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
89749,321918,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45723460g,2019-11-05,notice bibliographique et autorités,Livre audio,Mon père,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
89755,321925,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb457848544,2019-11-05,notice bibliographique et autorités,Livre audio,Soif,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
89756,321926,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45821701g,2019-11-05,notice bibliographique et autorités,Livre audio,"Millénium, Vol. 6 La fille qui devait mourir",NaN,NaN,6,...,True,False,False,True,False,False,False,False,True,True
89764,321935,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45824973m,2019-11-05,notice bibliographique et autorités,Livre audio,La cage dorée la vengeance d'une femme est dou...,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89765,321936,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45794301c,2019-11-05,notice bibliographique et autorités,Livre audio,Civilizations,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89766,321937,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45824983x,2019-11-05,notice bibliographique et autorités,Livre audio,Salina les trois exils,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89767,321938,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45794297z,2019-11-05,notice bibliographique et autorités,Livre,Une joie féroce,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
89768,321939,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb457943032,2019-11-05,notice bibliographique et autorités,Livre audio,Né d'aucune femme,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89770,321941,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45832652j,2019-11-05,notice bibliographique et autorités,Livre audio,"Les femmes écrivains Simone de Beauvoir, Margu...",NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
89772,321943,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45810817p,2019-11-05,notice bibliographique et autorités,Livre audio,L'automne à Pékin roman,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89773,321944,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb458108108,2019-11-05,notice bibliographique et autorités,Livre audio,Journal d'un amour perdu,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89774,321945,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb45810823m,2019-11-05,notice bibliographique et autorités,Livre audio,Octobre,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
89776,321947,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb46513927m,2019-11-05,notice bibliographique et autorités,Livre audio,Les choses humaines,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
89777,321948,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb465139179,2019-11-05,notice bibliographique et autorités,Livre audio,Le ciel par-dessus le toit,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
89780,321951,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb46513970r,2019-11-05,notice bibliographique et autorités,Livre audio,Pour un instant d'éternité,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
121730,378180,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb48621028n,2025-10-29,notice bibliographique et autorités,Livre,Dans la nuit solitaire,NaN,NaN,NaN,...,True,False,False,False,False,False,True,False,False,False

In [36]:
vdg_ko[
    (vdg_ko['B410v_'] != vdg_ko['B410v_bnf_'])
]

Empty DataFrame
Columns: [bib_record_id, bib_persistentid, bib_ark_bnf, bib_rbx_date_creation_notice, bib_rbx_vdg_action, bib_rbx_support, B200ae, B200h, B200i, B200v, B225a, B225h, B225i, B225v, B225x, B410a, B410t, B410v, B461t, B461v, bib_agence_cat, bib_pat, ccodes, bib_nb_items, public, genre, bib_alignement_bnf, B200ae_, B200h_, B200i_, B200v_, B225a_, B225h_, B225i_, B225v_, B225x_, B410a_, B410t_, B410v_, B461t_, B461v_, bib_record_id_bnf, bib_persistentid_bnf, bib_ark_bnf_bnf, bib_rbx_date_creation_notice_bnf, bib_rbx_vdg_action_bnf, bib_rbx_support_bnf, B200ae_bnf, B200h_bnf, B200i_bnf, B200v_bnf, B225a_bnf, B225h_bnf, B225i_bnf, B225v_bnf, B225x_bnf, B410a_bnf, B410t_bnf, B410v_bnf, B461t_bnf, B461v_bnf, bib_agence_cat_bnf, bib_pat_bnf, ccodes_bnf, bib_nb_items_bnf, B200ae_bnf_, B200h_bnf_, B200i_bnf_, B200v_bnf_, B225a_bnf_, B225h_bnf_, B225i_bnf_, B225v_bnf_, B225x_bnf_, B410a_bnf_, B410t_bnf_, B410v_bnf_, B461t_bnf_, B461v_bnf_]
Index: []

[0 rows x 79 columns]

In [38]:
vdg_ko[
    (vdg_ko['B461v_'] != vdg_ko['B461v_bnf_'])
]

,bib_record_id,bib_persistentid,bib_ark_bnf,bib_rbx_date_creation_notice,bib_rbx_vdg_action,bib_rbx_support,B200ae,B200h,B200i,B200v,...,B225a_bnf_,B225h_bnf_,B225i_bnf_,B225v_bnf_,B225x_bnf_,B410a_bnf_,B410t_bnf_,B410v_bnf_,B461t_bnf_,B461v_bnf_
55,249,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb35523005s,2014-06-30,notice bibliographique et autorités,Livre,Le corps dictionnaire bilingue,NaN,NaN,NaN,...,True,False,False,True,False,False,True,False,True,True
117,596,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb36606247w,2014-06-30,notice bibliographique et autorités,Livre,La Lecture et ses institutions 1700-1830,1,Prélude,NaN,...,False,False,False,False,False,False,False,False,True,True
125,647,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb321238752,2014-06-30,notice bibliographique et autorités,Livre,Le mannequin d'osier,NaN,NaN,NaN,...,True,False,False,True,False,False,True,False,True,True
181,1008,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb351277488,2014-06-30,notice bibliographique et autorités,Livre,Autobiographie de Giuliano di Sansevero,4,Les Puissances,NaN,...,False,False,False,False,False,False,False,False,True,True
182,1010,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb35129282j,2014-06-30,notice bibliographique et autorités,Livre,Autobiographie de Giuliano di Sansevero,5,Le Dernier des Sansevero,NaN,...,False,False,False,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121693,378060,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb486019997,2025-10-23,notice bibliographique et autorités,Livre,Coeur-Flambant,NaN,NaN,NaN,...,True,False,False,True,False,False,False,False,True,True
121795,378333,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb48630994w,2025-11-04,notice bibliographique et autorités,Livre,Chaos bang,NaN,NaN,NaN,...,True,False,False,True,False,False,False,False,True,True
121796,378337,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb48630984k,2025-11-04,notice bibliographique et autorités,Livre,Phénoménal,NaN,NaN,NaN,...,True,False,False,True,False,False,False,False,True,True
121798,378340,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb48626719t,2025-11-04,notice bibliographique et autorités,Livre,Le château des illusions,NaN,NaN,NaN,...,True,False,False,True,False,False,True,False,True,True
121819,378400,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb48635130n,2025-11-07,notice bibliographique et autorités,Livre,Le Noël carrément chaotique de Lottie Brooks,NaN,NaN,NaN,...,True,False,False,True,False,False,False,False,True,True

In [11]:
df['B464t_'].value_counts()

B464t_
False    232419
True        359
Name: count, dtype: int64

In [12]:
df[df['B464t_'] == True]

,bib_record_id,bib_persistentid,bib_ark_bnf,bib_rbx_date_creation_notice,bib_rbx_vdg_action,bib_rbx_support,B200ae,B200h,B200i,B200v,...,B410t_,B410v_,B461t_,B461v_,B462t_,B462v_,B463t_,B463v_,B464t_,B464v_
27584,55273,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb36182422x,2014-06-30,notice bibliographique et autorités,Livre,Intentions,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,True,False
32436,65587,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb35825645p,2014-06-30,notice bibliographique et autorités,Livre,Les aventures de Sherlock Holmes,1,NaN,NaN,...,True,True,False,False,False,False,False,False,True,False
35382,71174,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb35544637q,2014-06-30,notice bibliographique et autorités,Livre,Théâtre complet,2,Médée ; Hercule furieux ; Hercule sur l'Oeta ;...,NaN,...,True,False,False,False,False,False,False,False,True,False
60031,114418,http://www.mediathequederoubaix.fr/ark:/20179/...,NaN,2014-06-30,aucune action,Livre,Romans et œuvres de fiction non théâtrales,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,True,False
73320,141158,http://www.mediathequederoubaix.fr/ark:/20179/...,ark:/12148/cb39293716v,2014-06-30,notice bibliographique et autorités,Livre,Les introuvables de Philippe Carrese,NaN,NaN,NaN,...,True,True,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232754,379349,http://www.mediathequederoubaix.fr/ark:/20179/...,NaN,2025-11-27,autorités seulement,DVD,Peacock,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,True,False
232755,379350,http://www.mediathequederoubaix.fr/ark:/20179/...,NaN,2025-11-27,autorités seulement,DVD,La trilogie d'Oslo Rêves ; Amour ; Désir,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,True,False
232757,379352,http://www.mediathequederoubaix.fr/ark:/20179/...,NaN,2025-11-27,autorités seulement,DVD,Aux jours qui viennent,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,True,False
232759,379354,http://www.mediathequederoubaix.fr/ark:/20179/...,NaN,2025-11-27,autorités seulement,DVD,Kouté Vwa,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,True,False
232765,379360,http://www.mediathequederoubaix.fr/ark:/20179/...,NaN,2025-11-27,autorités seulement,DVD,The Handmaid's Tale,Saison 6,NaN,NaN,...,False,False,False,True,False,False,False,False,True,False

In [ ]:
vdg_ko[
    (vdg_ko['B200ae_'] == vdg_ko['B200ae_bnf_'])
    & (vdg_ko['B200h_'] == vdg_ko['B200h_bnf_'])
    & (vdg_ko['B200i_'] == vdg_ko['B200i_bnf_'])
    & (vdg_ko['B200v_'] == vdg_ko['B200v_bnf_'])
    & (vdg_ko['B225a_'] == vdg_ko['B225a_bnf_'])
    & (vdg_ko['B225h_'] == vdg_ko['B225h_bnf_'])
    & (vdg_ko['B225i_'] == vdg_ko['B225i_bnf_'])
    & (vdg_ko['B225v_'] == vdg_ko['B225v_bnf_'])
    & (vdg_ko['B225x_'] == vdg_ko['B225x_bnf_'])
    & (vdg_ko['B410a_'] == vdg_ko['B410a_bnf_'])
    & (vdg_ko['B410t_'] == vdg_ko['B410t_bnf_'])
    & (vdg_ko['B410v_'] == vdg_ko['B410v_bnf_'])
    & (vdg_ko['B461t_'] == vdg_ko['B461t_bnf_'])
    & (vdg_ko['B461v_'] == vdg_ko['B461v_bnf_'])
]